# Übungsblatt Pandas .map() .filter() .apply()

Eine gute Übersicht über die Pandas-Funktionen gibt es hier:

- [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [Pandas Series](https://pandas.pydata.org/pandas-docs/stable/reference/series.html)
- [Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html)

In den folgenden Aufgaben verwendet ihr einige der meist benutzten Funktionen von Pandas.

## Setup

In [1]:
import pandas as pd

## Aufgabe 1 - Emmisionsdaten Kanton Zürich

Der Kanton Zürich veröffentlicht auf seiner Webseite [https://opendata.swiss/de/dataset/luftschadstoffemissionen-im-kanton-zurich/resource/4c53c45a-d7dd-4268-8dbe-57abbc4dbf3d] die Messwerte der Luftqualität. Liest die Datenbeschreibung unter https://www.web.statistik.zh.ch/awel/ostluft_emissionsbilanzen/datenbeschreibung_emissionen.txt durch und ladet die Daten in ein DataFrame.
Das File steht unter dem Namen `emissionen_gemeinden_ostluft.csv` im Repo bereit. Es enthält die Emissionsdaten der Gemeinden im Kanton Zürich. 

Kleiner Tipp: Statt die Methode .head() oder .tail() zu verwenden, um einen Eindruck von den Daten zu bekommen, könnt ihr auch die Methode .sample() verwenden, um eine zufällige Zeile auszugeben. So bekommt ihr einen besseren Eindruck von den Daten, als wenn ihr nur die ersten oder letzten Zeilen betrachtet.

***1.*** Laden Sie die Daten herunter und lesen Sie die Daten in ein Pandas DataFrame ein.

In [2]:
import pandas as pd

df_emmissiondata = pd.read_csv("emissionen_gemeinden_ostluft.csv")

# zufällige Zeile ausgeben
df_emmissiondata.sample(10)

,jahr,substanz,hauptgruppe,untergruppe,gemeinde,emission,bfsnr,kanton,einheit,einheit_lang
15244,2015,NOx,Industrie,Flächenquellen Industrie,Adlikon,0.180566,21,ZH,t/a,Tonnen pro Jahr
67500,2020,NOx,Industrie,Punktquellen Zementwerke,Dielsdorf,0.000000,86,ZH,t/a,Tonnen pro Jahr
117007,2020,SO2,Dienstleistungen,Dienstleistungen Landschaftspflege,Fehraltorf,0.000052,172,ZH,t/a,Tonnen pro Jahr
60090,2020,NH3,Verkehr,Schifffahrt Fährlinien,Wil (ZH),0.000000,71,ZH,t/a,Tonnen pro Jahr
131839,2015,SO2,Haushalte,Haushalte andere Feuerwerk etc,Uster,0.025052,198,ZH,t/a,Tonnen pro Jahr
91102,2020,PM2.5,Dienstleistungen,Feuerungen Dienstleistungen Öl und Gas,Grüningen,0.005230,116,ZH,t/a,Tonnen pro Jahr
33435,2030,NMVOC,Verkehr,Schienenverkehr Bau-/Dienstzüge,Rheinau,0.004128,38,ZH,t/a,Tonnen pro Jahr
90991,2015,SO2,natürl. Emissionen,Emissionen aus Wäldern,Grüningen,0.000000,116,ZH,t/a,Tonnen pro Jahr
56806,2020,PM2.5,Verkehr,F-Gase: Transporte mit Kühlung,Rorbas,0.000000,68,ZH,t/a,Tonnen pro Jahr
10362,2020,NH3,Verkehr,F-Gase: Transporte mit Kühlung,Obfelden,0.000000,10,ZH,t/a,Tonnen pro Jahr

***2.*** Erstellen Sie eine Dictionary mit den verschiedenen Substanzen und ergänze die Dictionary mit den Namen der Substanzen.
- BC = Black Carbon
- CO = Kohlenmonoxid
- NH3 = Ammoniak
- NMVOC = Nichtmethanflüchtige organische Verbindungen
- NOx = Stickoxide
- PM10 = Partikel mit einem Durchmesser von 10 Mikrometer
- PM2.5 = Partikel mit einem Durchmesser von 2.5 Mikrometer
- SO2 = Schwefeldioxid

In [3]:
substanzenliste = {
    "BC": "Black Carbon",
    "CO": "Kohlenmonoxid",
    "NH3": "Ammoniak",
    "NOx": "Stickoxide",
    "NMVOC": "Nichtmethanoide flüchtige organische Verbindungen",
    "PM10": "Partikel mit einem Durchmesser von 10 Mikrometer",
    "PM2.5": "Partikel mit einem Durchmesser von 2.5 Mikrometer",
    "SO2": "Schwefeldioxid",
}

df_emmissiondata["substanz_bez"] = df_emmissiondata["substanz"].map(substanzenliste)
df_emmissiondata

,jahr,substanz,hauptgruppe,untergruppe,gemeinde,emission,bfsnr,kanton,einheit,einheit_lang,substanz_bez
0,2015,BC,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.000000,1,ZH,t/a,Tonnen pro Jahr,Black Carbon
1,2015,CO,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,2.048775,1,ZH,t/a,Tonnen pro Jahr,Kohlenmonoxid
2,2015,NH3,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.000006,1,ZH,t/a,Tonnen pro Jahr,Ammoniak
3,2015,NMVOC,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.113484,1,ZH,t/a,Tonnen pro Jahr,Nichtmethanoide flüchtige organische Verbindungen
4,2015,NOx,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.014328,1,ZH,t/a,Tonnen pro Jahr,Stickoxide
...,...,...,...,...,...,...,...,...,...,...,...
176035,2030,NMVOC,Verkehr,Zonenverkehr,Zürichsee (ZH),0.648574,9051,ZH-See,t/a,Tonnen pro Jahr,Nichtmethanoide flüchtige organische Verbindungen
176036,2030,NOx,Verkehr,Zonenverkehr,Zürichsee (ZH),0.146506,9051,ZH-See,t/a,Tonnen pro Jahr,Stickoxide
176037,2030,PM10,Verkehr,Zonenverkehr,Zürichsee (ZH),0.001390,9051,ZH-See,t/a,Tonnen pro Jahr,Partikel mit einem Durchmesser von 10 Mikrometer
176038,2030,PM2.5,Verkehr,Zonenverkehr,Zürichsee (ZH),0.001390,9051,ZH-See,t/a,Tonnen pro Jahr,Partikel mit einem Durchmesser von 2.5 Mikrometer
176039,2030,SO2,Verkehr,Zonenverkehr,Zürichsee (ZH),0.000261,9051,ZH-See,t/a,Tonnen pro Jahr,Schwefeldioxid

***3.*** Im Excel File "Gemeindestand.xlsx" sind die Gemeinden in der Schweiz aufgelistet. Lesen Sie die Daten in ein Pandas DataFrame ein.
Ergänze die Emissionsdaten mit den Bezirksnamen aus dem Excel File und finde heraus, welche Gemeinden nicht im Excel File aufgelistet sind.

Die Aufgabe in Schritten:
- Erstelle eine Zuordnung von Gemeindename → Bezirksname (z.B. als Series oder Dictionary) Tipp: Verwende die Methode .set_index() um den Gemeindename als Index zu setzen und dann die Spalte Bezirksname auszuwählen.
- Mappe die Bezirke auf den Emissionsdaten-DataFrame Tipp: Verwende die Methode .map() um die Bezirksnamen auf den Emissionsdaten-DataFrame zu mappen. Achte darauf, dass die Spalte mit den Gemeindennamen in beiden DataFrames den gleichen Namen hat.
- Zeige fehlende Bezirke (NaN) und gib die betroffenen Gemeinden aus Tipp: Verwende die Methode .isna() um die Zeilen mit fehlenden Bezirksangaben zu filtern und dann die Spalte mit den Gemeindennamen auszuwählen.
- Verwende die Methode .unique() um die einzigartigen Gemeinden auszugeben, die nicht im Excel File aufgelistet sind.

In [ ]:
df_gemeinstand = pd.read_excel("Gemeindestand.xlsx")
df_gemeinstand

c:\Daten\Repos\Unterricht\NGDS-DZP\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Hist.-Nummer,Kanton,Bezirks-nummer,Bezirksname,BFS Gde-nummer,Gemeindename,Datum der Aufnahme
0,13256,ZH,101,Affoltern,1,Aeugst am Albis,1976-11-15
1,11742,ZH,101,Affoltern,2,Affoltern am Albis,1848-09-12
2,11801,ZH,101,Affoltern,3,Bonstetten,1848-09-12
3,11992,ZH,101,Affoltern,4,Hausen am Albis,1911-01-01
4,12249,ZH,101,Affoltern,5,Hedingen,1848-09-12
...,...,...,...,...,...,...,...
2126,14965,JU,2603,Porrentruy,6808,Clos du Doubs,2009-01-01
2127,16120,JU,2603,Porrentruy,6809,Haute-Ajoie,2018-01-01
2128,14969,JU,2603,Porrentruy,6810,La Baroche,2009-01-01
2129,16627,JU,2603,Porrentruy,6811,Damphreux-Lugnez,2023-01-01
2130,16654,JU,2603,Porrentruy,6812,Basse-Vendline,2024-01-01

In [5]:
# 1. Erstelle eine Zuordnung von Gemeindename → Bezirksname
gemeinde_to_bezirk = df_gemeinstand.set_index("Gemeindename")["Bezirksname"]
gemeinde_to_bezirk

Gemeindename
Aeugst am Albis        Affoltern
Affoltern am Albis     Affoltern
Bonstetten             Affoltern
Hausen am Albis        Affoltern
Hedingen               Affoltern
                         ...
Clos du Doubs         Porrentruy
Haute-Ajoie           Porrentruy
La Baroche            Porrentruy
Damphreux-Lugnez      Porrentruy
Basse-Vendline        Porrentruy
Name: Bezirksname, Length: 2131, dtype: str

In [6]:
# 2. Mappe die Bezirke auf den Emissionsdaten-DataFrame
df_emmissiondata["bezirk"] = df_emmissiondata["gemeinde"].map(gemeinde_to_bezirk)

In [7]:
# 3. Zeige fehlende Bezirke (NaN) und gib die betroffenen Gemeinden aus
fehlende_gemeinden = df_emmissiondata.loc[
    df_emmissiondata["bezirk"].isna(), "gemeinde"
].unique()

fehlende_gemeinden

<StringArray>
['Adlikon', 'Humlikon', 'Zürichsee (ZH)']
Length: 3, dtype: str

***4.*** Löschen die Bezirke ohne Angaben aus der Emmisionsdatenliste. 

Tipp: Verwende die Methode .notna(), um die Zeilen mit fehlenden Bezirksangaben zu filtern.

In [8]:
# Lösche die Zeilen mit NaN Werten in der Spalte Bezirk
df_emmissiondata_non_na = df_emmissiondata[df_emmissiondata["bezirk"].notna()]

# Alternativ
df_emmissiondata_non_na = df_emmissiondata.dropna(subset=["bezirk"])


df_emmissiondata_non_na

,jahr,substanz,hauptgruppe,untergruppe,gemeinde,emission,bfsnr,kanton,einheit,einheit_lang,substanz_bez,bezirk
0,2015,BC,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.000000,1,ZH,t/a,Tonnen pro Jahr,Black Carbon,Affoltern
1,2015,CO,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,2.048775,1,ZH,t/a,Tonnen pro Jahr,Kohlenmonoxid,Affoltern
2,2015,NH3,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.000006,1,ZH,t/a,Tonnen pro Jahr,Ammoniak,Affoltern
3,2015,NMVOC,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.113484,1,ZH,t/a,Tonnen pro Jahr,Nichtmethanoide flüchtige organische Verbindungen,Affoltern
4,2015,NOx,Dienstleistungen,Dienstleistungen Landschaftspflege,Aeugst am Albis,0.014328,1,ZH,t/a,Tonnen pro Jahr,Stickoxide,Affoltern
...,...,...,...,...,...,...,...,...,...,...,...,...
174955,2030,NMVOC,Verkehr,Zonenverkehr,Greifensee,2.181485,9040,ZH-See,t/a,Tonnen pro Jahr,Nichtmethanoide flüchtige organische Verbindungen,Uster
174956,2030,NOx,Verkehr,Zonenverkehr,Greifensee,0.492774,9040,ZH-See,t/a,Tonnen pro Jahr,Stickoxide,Uster
174957,2030,PM10,Verkehr,Zonenverkehr,Greifensee,0.004675,9040,ZH-See,t/a,Tonnen pro Jahr,Partikel mit einem Durchmesser von 10 Mikrometer,Uster
174958,2030,PM2.5,Verkehr,Zonenverkehr,Greifensee,0.004675,9040,ZH-See,t/a,Tonnen pro Jahr,Partikel mit einem Durchmesser von 2.5 Mikrometer,Uster
174959,2030,SO2,Verkehr,Zonenverkehr,Greifensee,0.000877,9040,ZH-See,t/a,Tonnen pro Jahr,Schwefeldioxid,Uster

***5.*** Schau dir kurz an welche Hauptgruppen, Untergruppen und Bezirken in der Tabelle vorkommen.

In [9]:
df_emmissiondata["untergruppe"].value_counts()

untergruppe
Feuerungen Haushalte Öl und Gas                11736
Dienstleistungen Landschaftspflege              3912
Feuerungen Dienstleistungen Holz und Kohle      3912
Feuerungen Dienstleistungen Öl und Gas          3912
F-Gase: Läden und Gebäude mit Klimaanlagen      3912
Feuerungen Haushalte Holz und Kohle             3912
Haushalte andere Brände etc                     3912
Haushalte andere Feuerwerk etc                  3912
Haushalte andere Private etc                    3912
Lösungsmittel Konsumprodukte                    3912
Maschinen Garten und Hobby                      3912
Baumaschinen                                    3912
Deponien                                        3912
Flächenquellen Industrie                        3912
Industriefahrzeuge                              3912
Kläranlagen                                     3912
Kompostierung                                   3912
Lösungsmittel Industrie                         3912
Pistenfahrzeuge                                 3912
Punktquellen KVA                                3912
Punktquellen Zementwerke                        3912
Verluste Gasnetz                                3912
Weitere Punktquellen OL                         3912
Abfallverbrennung Land- und Forstwirtschaft     3912
Feuerungen Landwirtschaft Holz                  3912
Forstwirtschaftliche Maschinen                  3912
Landwirtschaftliche Maschinen                   3912
Landwirtschaftliche Nutzflächen                 3912
Ställe                                          3912
Vergärung                                       3912
Weiden                                          3912
Emissionen aus Wäldern                          3912
F-Gase: Klimaanlagen Motorfahrzeuge             3912
F-Gase: Transporte mit Kühlung                  3912
Flugverkehr Genf                                3912
Flugverkehr Zürich                              3912
Rheinschifffahrt                                3912
Schienenverkehr Bau-/Dienstzüge                 3912
Schienenverkehr Rangieren                       3912
Schifffahrt Fährlinien                          3912
Schifffahrt Seen                                3912
Strassenverkehr                                 3912
Zonenverkehr                                    3912
Name: count, dtype: int64

In [10]:
df_emmissiondata["hauptgruppe"].value_counts()

hauptgruppe
Industrie             46944
Verkehr               43032
Haushalte             35208
Land- und Forstw.     31296
Dienstleistungen      15648
natürl. Emissionen     3912
Name: count, dtype: int64

In [11]:
df_emmissiondata["bezirk"].value_counts()

bezirk
Bülach         23760
Dielsdorf      23760
Andelfingen    21600
Winterthur     20520
Affoltern      15120
Hinwil         11880
Meilen         11880
Dietikon       11880
Pfäffikon      10800
Uster          10800
Horgen          9720
Zürich          1080
Name: count, dtype: int64

***6.*** Filtere für die Bezirke Hinwil und Uster die Daten für die Substanz PM10 und PM2.5. 

Summiere die Werte für die Bezirke Hinwil und Uster pro Jahr. Die einfachste Methode ist die Methode .groupby().

In [12]:
# Filtere für die Bezirke Hinwil und Uster die Daten für die Substanz PM10 und PM2.5.
df_filter = df_emmissiondata_non_na[
    (
        (df_emmissiondata_non_na["bezirk"] == "Hinwil")
        | (df_emmissiondata_non_na["bezirk"] == "Uster")
    )
    & (df_emmissiondata_non_na["substanz"].isin(["PM10", "PM2.5"]))
]

df_filter
# Summiere die Emmissionswerte für die Bezirke Hinwil und Uster pro Jahr. Die einfachste Methode ist die Methode .df_filter.groupby(["jahr"]).
df_filter.groupby(["bezirk", "jahr"])["emission"].sum()

bezirk  jahr
Hinwil  2015    230.086307
        2020    225.508609
        2030    210.661382
Uster   2015    237.783501
        2020    232.361286
        2030    219.879083
Name: emission, dtype: float64

## Aufgabe 2 - Wetterdaten reduzieren

***0.*** Lies die Wetterdaten aus der Datei "ugz_ogd_meteo_d1_2023.csv" in ein DataFrame ein.

***1.***
An wie vielen Tagen wurde die Temperatur zwischen 5 und 10 Grad an der Rosengartenstrasse gemessen?

Für das filtern des DataFrames gibt es unterschiedliche Ansätze. Verwende die unterschiedlichen Methoden um die Anzahl der Tage zu ermitteln und mache ein Zeitmessung.

- Boolesche Indizierung: Filtert Daten basierend auf einem booleschen Ausdruck, der auf einer Spalte oder einer Zeile basiert.
- `query()`: Filtert Daten basierend auf einem Ausdruck, der in einer speziellen Abfragesprache (ähnlich SQL) geschrieben ist.
- `.loc[]` und `.iloc[]` : Filtert Daten basierend auf den Achsenbezeichnungen (wie Spaltennamen oder Indexwerte)

In [13]:
import pandas as pd

df = pd.read_csv("ugz_ogd_meteo_d1_2023.csv")
df.sample(5)

,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
1262,2023-04-08T00:00+0100,Zch_Stampfenbachstrasse,RainDur,d1,min,54.03,provisorisch
4300,2023-11-27T00:00+0100,Zch_Rosengartenstrasse,RainDur,d1,min,359.22,provisorisch
3976,2023-11-02T00:00+0100,Zch_Rosengartenstrasse,p,d1,hPa,943.82,provisorisch
962,2023-03-16T00:00+0100,Zch_Stampfenbachstrasse,T,d1,°C,6.74,provisorisch
1792,2023-05-18T00:00+0100,Zch_Rosengartenstrasse,p,d1,hPa,969.63,provisorisch

In [14]:
df_filtered = df.query(
    "Standort == 'Zch_Rosengartenstrasse' & Wert > 5 & Wert < 10 & Parameter == 'T'"
)
len(df_filtered)

88

In [15]:
%%timeit
df_filtered = df.query("Standort == 'Zch_Rosengartenstrasse' & Wert > 5 & Wert < 10 & Parameter == 'T'")

2.83 ms ± 889 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [16]:
df_filtered = df.loc[
    (df["Standort"] == "Zch_Rosengartenstrasse")
    & (df["Wert"] > 5)
    & (df["Wert"] < 10)
    & (df["Parameter"] == "T")
]
print(len(df_filtered))

88

In [17]:
%%timeit 
df_filtered = df.loc[
    (df["Standort"] == "Zch_Rosengartenstrasse") & 
    (df["Wert"] > 5) & 
    (df["Wert"] < 10) & 
    (df["Parameter"] == "T")]

2.16 ms ± 104 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [18]:
df_filtered = df[
    (df["Standort"] == "Zch_Rosengartenstrasse")
    & (df["Wert"] > 5)
    & (df["Wert"] < 10)
    & (df["Parameter"] == "T")
]
len(df_filtered)

88

In [19]:
%%timeit 
df_filtered = df[
                (df["Standort"] == "Zch_Rosengartenstrasse") & 
                (df["Wert"] > 5) & 
                (df["Wert"] < 10) & 
                (df["Parameter"] == "T")
                ]

2.01 ms ± 241 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

1.1 Was sind die Vor- und Nachteile der unterschiedlichen Methoden?
1. Direkt mit booleschem Indexing (df[...])
- Vorteile:
  - Schnellste Methode (minimaler Overhead)
  - Klarer, wenn nur Zeilen gefiltert werden 
- Achtung:
  - Nur für Zeilenfilter, kein Zugriff auf Spalten
2. Mit .loc[]
   - Vorteile:
     - Sehr gut lesbar und robust
     - Ermöglicht auch gleichzeitigen Spaltenzugriff (z.B. df.loc[...,'Spalte'])
   - Etwas langsamer als boolesches Indexing, wegen zusätzlichem Funktionalität
3. Mit .query()
   - Vorteile:
     - Sehr leserlich, besonders bei vielen Bedingungen
     - Gut für interaktive Analysen
   - Langsamste Methode, da 
     - String muss geparsed und interpretiert werden
     - Kann bei Sonderzeichen oder komplexen Spaltennamen problematisch sein
  
1.2 Weshalb ist die .loc[] Methode robuster als die booleschem Indexing (df[...]) Methode?

1. Explizite Absicht:
   - .loc[rows] sagt klar: „Ich greife auf Zeilen mit bestimmten Labels oder Bedingungen zu.“
   - df[condition] funktioniert nur, wenn condition ein boolescher Vektor ist.
   - Wenn du versehentlich etwas anderes in df[...] reinschreibst (z. B. ein einzelner Spaltenname), bekommst du etwas ganz anderes zurück:
   - Ambiguität: df[...] kann Spaltenzugriff oder Filter sein. .loc[...] ist eindeutig.
  
2. Erweiterbarkeit mit Spaltenzugriff
   - .loc[rows, columns] (df.loc[(df["Parameter"] == "T"),["Wert", "Standort"]]) erlaubt später einfach die Auswahl von Spalten zusätzlich zur Filterung:
   - Mit df[condition] geht das nicht direkt. Man müsste danach nochmal df_filtered[["Wert", "Standort"]] schreiben.
   - 

3. Mehr Fehlerschutz bei komplexem Code
    - Bei verschachteltem Code ist .loc deutlicher und besser gegen Fehler abgesichert, weil die Absicht klar ist: „Ich will Zeilen mit diesen Bedingungen.“


Fazit: Für produktiven, stabilen Code ist .loc[] robuster und sicherer – auch wenn df[...] minimal schneller ist.

***2.*** Wie viele Minuten hat es im Jahr an der Stampfenbachstrasse geregnet?
Filtere die Daten mit den oben genannten Methoden und führe eine Zeitmessung durch.

In [20]:
%%timeit 
df.query("Standort == 'Zch_Stampfenbachstrasse' & Parameter == 'RainDur'").Wert.sum()

3.13 ms ± 235 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [21]:
%%timeit 
df[
                (df["Standort"] == 'Stampfenbachstrasse') & 
                (df["Parameter"] == 'rain_duration')
                ].Wert.sum()

1.86 ms ± 206 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [22]:
%%timeit 
df.loc[
                (df["Standort"] == 'Stampfenbachstrasse') & 
                (df["Parameter"] == 'rain_duration')
                ].Wert.sum()

1.76 ms ± 103 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

## Aufgabe 3 - BMI-Rechner für Fitnessmitglieder

Wir kennen das Beispiel mit dem BMI-Rechner noch von früheren Aufgaben.
Nun könnt ihr das gelernte an diesem Beispiel üben

***0.*** Lies die Daten aus der Datei "ko_fitness_memberlist.csv" in ein DataFrame ein.

***1.*** Verwende die map() bzw. apply()-Funktion um die Spalten bmi und bmi-meldung zu berechnen

In [23]:
import pandas as pd


def bmi_meldung(bmi):

    return_val = "Unter 18.5: Untergewicht."
    if bmi > 40:
        return_val = "Über 40: Adipositas Grad III."
    elif bmi >= 35:
        return_val = "35 - 39.9: Adipositas Grad II."
    elif bmi >= 30:
        return_val = "30 - 34.9: Adipositas (Fettleibigkeit) Grad I."
    elif bmi >= 25:
        return_val = "25 - 29.9: Übergewicht/ Präadipositas."
    elif bmi >= 18.5:
        return_val = "18.5 - 24.9: Normalgewicht."
    return return_val


def bmi_rechner(koerper_gewicht, koerper_groesse):
    return koerper_gewicht / koerper_groesse**2

In [24]:
df_member_list = pd.read_csv("ko_fitness_memberlist.csv", delimiter=";")


df_member_list["BMI"] = df_member_list.apply(
    lambda row: bmi_rechner(row["Gewicht"], row["Grösse"]), axis=1
)

df_member_list["BMI Meldung"] = df_member_list["BMI"].map(bmi_meldung)

df_member_list

,Vorname,Name,Gewicht,Grösse,Geschlecht,BMI,BMI Meldung
0,Suzanne,Milam,64,1.76,w,20.661157,18.5 - 24.9: Normalgewicht.
1,Louis,Finch,99,1.81,m,30.218858,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
2,Shannon,Francois,101,1.80,w,31.172840,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
3,Michael,Sinisi,67,1.80,m,20.679012,18.5 - 24.9: Normalgewicht.
4,Robert,Mcdonough,90,1.92,m,24.414062,18.5 - 24.9: Normalgewicht.
...,...,...,...,...,...,...,...
95,Geraldine,Edwards,98,1.54,w,41.322314,Über 40: Adipositas Grad III.
96,Charles,Martin,81,1.91,m,22.203339,18.5 - 24.9: Normalgewicht.
97,Beth,Rozar,72,1.83,w,21.499597,18.5 - 24.9: Normalgewicht.
98,Charles,Owens,98,1.67,m,35.139302,35 - 39.9: Adipositas Grad II.
99,Lori,Nichols,81,1.83,w,24.187046,18.5 - 24.9: Normalgewicht.

***2.*** Finde heraus, welche Mitglieder übergewichtig sind und wieviele Männer bzw. Frauen untergewichtig sind.

In [25]:
overweight_members = df_member_list.loc[df_member_list["BMI"] > 25]
overweight_members

,Vorname,Name,Gewicht,Grösse,Geschlecht,BMI,BMI Meldung
1,Louis,Finch,99,1.81,m,30.218858,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
2,Shannon,Francois,101,1.80,w,31.172840,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
8,William,Waters,94,1.51,m,41.226262,Über 40: Adipositas Grad III.
9,Margaret,Clifford,101,1.57,w,40.975293,Über 40: Adipositas Grad III.
10,Gladys,England,84,1.68,w,29.761905,25 - 29.9: Übergewicht/ Präadipositas.
...,...,...,...,...,...,...,...
91,Barbara,Baker,78,1.71,w,26.674874,25 - 29.9: Übergewicht/ Präadipositas.
92,Reggie,Ortiz,75,1.72,m,25.351541,25 - 29.9: Übergewicht/ Präadipositas.
93,Mary,Rivers,99,1.81,w,30.218858,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
95,Geraldine,Edwards,98,1.54,w,41.322314,Über 40: Adipositas Grad III.
98,Charles,Owens,98,1.67,m,35.139302,35 - 39.9: Adipositas Grad II.

In [26]:
overweight_male = overweight_members.loc[overweight_members["Geschlecht"] == "m"]
overweight_male

,Vorname,Name,Gewicht,Grösse,Geschlecht,BMI,BMI Meldung
1,Louis,Finch,99,1.81,m,30.218858,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
8,William,Waters,94,1.51,m,41.226262,Über 40: Adipositas Grad III.
11,Jim,Wampler,82,1.70,m,28.373702,25 - 29.9: Übergewicht/ Präadipositas.
12,Jose,Moris,99,1.73,m,33.078285,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
15,Brian,Kimbrough,93,1.91,m,25.492722,25 - 29.9: Übergewicht/ Präadipositas.
17,Carlton,Keating,73,1.61,m,28.162494,25 - 29.9: Übergewicht/ Präadipositas.
19,Derek,Willett,96,1.59,m,37.973181,35 - 39.9: Adipositas Grad II.
20,Dwayne,Walker,89,1.78,m,28.089888,25 - 29.9: Übergewicht/ Präadipositas.
22,Carlton,Cremona,96,1.72,m,32.449973,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
23,David,Dixon,92,1.74,m,30.387105,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
27,William,Stinnett,82,1.73,m,27.398176,25 - 29.9: Übergewicht/ Präadipositas.
29,David,Hillin,80,1.77,m,25.535446,25 - 29.9: Übergewicht/ Präadipositas.
30,Scott,Gleason,102,1.54,m,43.008939,Über 40: Adipositas Grad III.
34,John,Hallett,70,1.51,m,30.700408,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
35,Kirk,Maldonado,102,1.75,m,33.306122,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
38,Hans,Murphy,90,1.59,m,35.599858,35 - 39.9: Adipositas Grad II.
40,Jack,Sutherland,94,1.85,m,27.465303,25 - 29.9: Übergewicht/ Präadipositas.
42,Brian,Draper,91,1.82,m,27.472527,25 - 29.9: Übergewicht/ Präadipositas.
43,Brandon,Williams,98,1.56,m,40.269560,Über 40: Adipositas Grad III.
45,Gary,Miller,70,1.65,m,25.711662,25 - 29.9: Übergewicht/ Präadipositas.
46,William,George,63,1.52,m,27.268006,25 - 29.9: Übergewicht/ Präadipositas.
51,Donnie,Goodman,84,1.56,m,34.516765,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
53,Carl,Pratt,93,1.72,m,31.435911,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
54,Lawrence,Bishop,101,1.71,m,34.540542,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
56,John,Butts,100,1.88,m,28.293345,25 - 29.9: Übergewicht/ Präadipositas.
57,John,Frederick,102,1.74,m,33.690052,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
62,Jason,James,93,1.59,m,36.786520,35 - 39.9: Adipositas Grad II.
70,Michael,Gaede,73,1.70,m,25.259516,25 - 29.9: Übergewicht/ Präadipositas.
71,Keith,Mason,75,1.58,m,30.043262,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
76,Charles,Lemaster,75,1.60,m,29.296875,25 - 29.9: Übergewicht/ Präadipositas.
84,Robert,Spano,64,1.57,m,25.964542,25 - 29.9: Übergewicht/ Präadipositas.
88,Matthew,Odonnell,90,1.68,m,31.887755,30 - 34.9: Adipositas (Fettleibigkeit) Grad I.
90,James,Fox,104,1.71,m,35.566499,35 - 39.9: Adipositas Grad II.
92,Reggie,Ortiz,75,1.72,m,25.351541,25 - 29.9: Übergewicht/ Präadipositas.
98,Charles,Owens,98,1.67,m,35.139302,35 - 39.9: Adipositas Grad II.

In [27]:
underweight_female = df_member_list.loc[
    (df_member_list["Geschlecht"] == "w") & (df_member_list["BMI"] < 18.5)
]

***3.*** Berechne die Durschnittsgrösse, -gewicht und BMI aller 

- männlichen Mitglieder, welche grösser als 1.80m sind.
- weiblichen Mitglieder, die untergewichtig sind
- übergewichtigen Mitglieder

Versuche die Aufgabe mit einer Methode-Chaining zu lösen.

In [28]:
# Berechne die Durschnittsgrösse, -gewicht und BMI aller männlichen Mitglieder, welche grösser als 1.80m sind.
average_over_180_male = (
    df_member_list.loc[
        (df_member_list["Geschlecht"] == "m") & (df_member_list["Grösse"] > 1.8)
    ]
    .filter(["Grösse", "Gewicht", "BMI"])
    .mean()
)
average_over_180_male


average_over_180_male = df_member_list.loc[
    (df_member_list["Geschlecht"] == "m") & (df_member_list["Grösse"] > 1.8),
    ["Grösse", "Gewicht", "BMI"],
].mean()

average_over_180_male

Grösse      1.872667
Gewicht    79.466667
BMI        22.722508
dtype: float64

In [29]:
# Berechne die Durschnittsgrösse, -gewicht und BMI aller  weiblichen Mitglieder, welche die Untergewichtig sind
average_underweighted_female = df_member_list.loc[
    (df_member_list["Geschlecht"] == "w") & (df_member_list["BMI"] < 18.5),
    ["Grösse", "Gewicht", "BMI"],
].mean()
average_underweighted_female

Grösse      1.890000
Gewicht    58.200000
BMI        16.317872
dtype: float64

In [ ]:
# Berechne die Durschnittsgrösse, -gewicht und BMI aller  übergewichtigen Mitglieder

average_overweighted = df_member_list.loc[
    df_member_list["BMI"] > 25, ["Grösse", "Gewicht", "BMI"]
].mean()
average_overweighted

Grösse      1.678361
Gewicht    87.836066
BMI        31.351407
dtype: float64

: